#!/usr/bin/env python3
"""Build thesis-ready figures from baseline vs exclude-flagged comparison."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create thesis figure pack from sensitivity comparison CSV"
    )
    parser.add_argument(
        "--comparison-csv",
        default=(
            "results/stages/07_network/sensitivity_exclude_flagged/comparison/"
            "baseline_vs_exclude_flagged_comparison.csv"
        ),
        help="Comparison CSV generated by 08f_compare_network_sensitivity.py",
    )
    parser.add_argument(
        "--output-dir",
        default=(
            "results/stages/07_network/sensitivity_exclude_flagged/"
            "thesis_figures"
        ),
        help="Directory for thesis-ready plots and compact tables",
    )
    parser.add_argument("--dpi", type=int, default=240, help="Figure DPI")
    return parser.parse_args()


def resolve_base(path_like: str) -> Path:
    path = Path(path_like)
    if path.is_absolute():
        return path
    cwd_candidate = (Path.cwd() / path).resolve()
    if cwd_candidate.exists():
        return cwd_candidate
    return (REPO_ROOT / path).resolve()


def read_required_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    return pd.read_csv(path)


def _condition_order(df: pd.DataFrame) -> list[str]:
    return df.sort_values("condition")["condition"].astype(str).tolist()


def plot_profiles_delta(df: pd.DataFrame, out_file: Path, dpi: int) -> None:
    plot_df = df.sort_values("d_profiles").copy()
    labels = plot_df["condition"].astype(str).tolist()
    values = plot_df["d_profiles"].astype(int).tolist()

    colors = ["#E45756" if v < 0 else "#54A24B" for v in values]

    fig_h = max(4.2, 0.46 * len(labels) + 1.8)
    fig, ax = plt.subplots(figsize=(9.0, fig_h))
    bars = ax.barh(labels, values, color=colors)
    ax.axvline(0, color="#374151", linewidth=1.0)
    ax.set_xlabel("Profile count change (exclude-flagged - baseline)")
    ax.set_title("Sensitivity impact on pseudobulk profile counts")
    ax.grid(axis="x", linestyle="--", alpha=0.25)

    for bar, value in zip(bars, values):
        x = value + (0.2 if value >= 0 else -0.2)
        ha = "left" if value >= 0 else "right"
        ax.text(x, bar.get_y() + bar.get_height() / 2, str(value),
                va="center", ha=ha, fontsize=9)

    fig.tight_layout()
    fig.savefig(str(out_file), dpi=dpi, bbox_inches="tight", pad_inches=0.1)
    plt.close(fig)


def _metric_pair_plot(
    df: pd.DataFrame,
    out_file: Path,
    metric_base: str,
    metric_sens: str,
    xlabel: str,
    title: str,
    dpi: int,
) -> None:
    plot_df = df.sort_values(metric_base).copy()
    y = np.arange(plot_df.shape[0])
    base = plot_df[metric_base].to_numpy(dtype=float)
    sens = plot_df[metric_sens].to_numpy(dtype=float)
    labels = plot_df["condition"].astype(str).tolist()

    fig_h = max(4.6, 0.44 * len(labels) + 1.9)
    fig, ax = plt.subplots(figsize=(9.6, fig_h))

    for yi, xb, xs in zip(y, base, sens):
        ax.plot([xb, xs], [yi, yi], color="#9CA3AF", linewidth=2.0, zorder=1)

    ax.scatter(base, y, color="#4C78A8", s=55, label="Baseline", zorder=2)
    ax.scatter(
        sens,
        y,
        color="#F58518",
        marker="s",
        s=50,
        label="Exclude-flagged",
        zorder=3,
    )

    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    ax.grid(axis="x", linestyle="--", alpha=0.25)
    ax.legend(loc="best", frameon=False)

    fig.tight_layout()
    fig.savefig(str(out_file), dpi=dpi, bbox_inches="tight", pad_inches=0.1)
    plt.close(fig)


def plot_hub_jaccard(df: pd.DataFrame, out_file: Path, dpi: int) -> None:
    plot_df = df.sort_values("hub_jaccard_top20", ascending=True).copy()
    labels = plot_df["condition"].astype(str).tolist()
    values = plot_df["hub_jaccard_top20"].astype(float).tolist()

    fig_h = max(4.2, 0.44 * len(labels) + 1.8)
    fig, ax = plt.subplots(figsize=(9.2, fig_h))
    bars = ax.barh(labels, values, color="#72B7B2")
    ax.set_xlim(0.0, 1.0)
    ax.set_xlabel("Jaccard overlap of top-20 hubs")
    ax.set_title("Hub stability after excluding flagged profiles")
    ax.grid(axis="x", linestyle="--", alpha=0.25)

    for bar, value in zip(bars, values):
        ax.text(
            min(0.99, value + 0.02),
            bar.get_y() + bar.get_height() / 2,
            f"{value:.3f}",
            va="center",
            fontsize=9,
        )

    fig.tight_layout()
    fig.savefig(str(out_file), dpi=dpi, bbox_inches="tight", pad_inches=0.1)
    plt.close(fig)


def write_summary_tables(df: pd.DataFrame, out_dir: Path) -> None:
    keep = [
        "condition",
        "profiles_base",
        "profiles_sens",
        "d_profiles",
        "power_base",
        "power_sens",
        "nodes_base",
        "nodes_sens",
        "d_nodes",
        "edges_base",
        "edges_sens",
        "d_edges",
        "hub_jaccard_top20",
    ]
    compact = df[keep].sort_values("condition").reset_index(drop=True)
    compact.to_csv(out_dir / "table_sensitivity_key_deltas.csv", index=False)


def write_readme(out_dir: Path) -> None:
    lines = [
        "# Sensitivity thesis figure pack",
        "",
        "Inputs:",
        "- baseline_vs_exclude_flagged_comparison.csv",
        "",
        "Outputs:",
        "- fig_profiles_delta.png",
        "- fig_nodes_baseline_vs_sensitivity.png",
        "- fig_edges_baseline_vs_sensitivity.png",
        "- fig_hub_overlap_jaccard.png",
        "- table_sensitivity_key_deltas.csv",
    ]
    (out_dir / "README.md").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    comparison_csv = resolve_base(args.comparison_csv)
    out_dir = resolve_base(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = read_required_csv(comparison_csv)
    if df.empty:
        raise ValueError("Comparison CSV is empty; nothing to plot")

    plot_profiles_delta(
        df,
        out_file=out_dir / "fig_profiles_delta.png",
        dpi=int(args.dpi),
    )

    _metric_pair_plot(
        df,
        out_file=out_dir / "fig_nodes_baseline_vs_sensitivity.png",
        metric_base="nodes_base",
        metric_sens="nodes_sens",
        xlabel="Number of visible network genes (nodes)",
        title="Baseline vs exclude-flagged: node counts",
        dpi=int(args.dpi),
    )

    _metric_pair_plot(
        df,
        out_file=out_dir / "fig_edges_baseline_vs_sensitivity.png",
        metric_base="edges_base",
        metric_sens="edges_sens",
        xlabel="Number of visible network connections (edges)",
        title="Baseline vs exclude-flagged: edge counts",
        dpi=int(args.dpi),
    )

    plot_hub_jaccard(
        df,
        out_file=out_dir / "fig_hub_overlap_jaccard.png",
        dpi=int(args.dpi),
    )

    write_summary_tables(df, out_dir)
    write_readme(out_dir)

    print(f"Wrote thesis figure pack to: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
